// @generated by pi-protocol generate; DO NOT EDIT.
// contract-digest: sha256:b181010c055671378cce65f1bed31e00748b6dde16625835faaf9c5a45919810
import type { ProtocolAgentExecutor, ProtocolHandler } from "@kybernetria/pi-protocol/core";

export const PROTOCOL_NODE_ID = "pi_pe" as const;
export const PROTOCOL_TARGETS = {
  catalog: "pi_pe.catalog",
  describe_target: "pi_pe.describe_target",
  validate_pipeline: "pi_pe.validate_pipeline",
  save_pipeline: "pi_pe.save_pipeline",
  get_pipeline: "pi_pe.get_pipeline",
  list_pipelines: "pi_pe.list_pipelines",
  delete_pipeline: "pi_pe.delete_pipeline",
  run_pipeline: "pi_pe.run_pipeline",
  dry_run_mapping: "pi_pe.dry_run_mapping",
  reload_pipelines: "pi_pe.reload_pipelines",
} as const;

export type ProtocolProvideName = "catalog" | "describe_target" | "validate_pipeline" | "save_pipeline" | "get_pipeline" | "list_pipelines" | "delete_pipeline" | "run_pipeline" | "dry_run_mapping" | "reload_pipelines";
export type ProtocolBinding = ProtocolHandler | ProtocolAgentExecutor;
export type ProtocolBindings = {
  "catalog": ProtocolBinding;
  "describe_target": ProtocolBinding;
  "validate_pipeline": ProtocolBinding;
  "save_pipeline": ProtocolBinding;
  "get_pipeline": ProtocolBinding;
  "list_pipelines": ProtocolBinding;
  "delete_pipeline": ProtocolBinding;
  "run_pipeline": ProtocolBinding;
  "dry_run_mapping": ProtocolBinding;
  "reload_pipelines": ProtocolBinding;
};

export type CatalogInput = { effects?: readonly string[]; executionType?: "handler" | "agent"; generated?: boolean; limit?: number; nodeId?: string; query?: string; tags?: readonly string[]; };
export type CatalogOutput = Record<string, never>;
export type DescribeTargetInput = { target: string; };
export type DescribeTargetOutput = Record<string, never>;
export type ValidatePipelineInput = { spec: Record<string, never>; };
export type ValidatePipelineOutput = Record<string, never>;
export type SavePipelineInput = { allowRuntimeOnly?: boolean; spec: Record<string, never>; };
export type SavePipelineOutput = Record<string, never>;
export type GetPipelineInput = { id: string; };
export type GetPipelineOutput = Record<string, never>;
export type ListPipelinesInput = Record<string, never>;
export type ListPipelinesOutput = Record<string, never>;
export type DeletePipelineInput = { confirm: boolean; id: string; };
export type DeletePipelineOutput = Record<string, never>;
export type RunPipelineInput = { id: string; input: unknown; };
export type RunPipelineOutput = Record<string, never>;
export type DryRunMappingInput = { id?: string; pipelineInput: unknown; spec?: Record<string, never>; stepOutputs?: Record<string, never>; };
export type DryRunMappingOutput = Record<string, never>;
export type ReloadPipelinesInput = Record<string, never>;
export type ReloadPipelinesOutput = Record<string, never>;
